media:
  - name: blog_assets
    label: Blog assets
    input: public/assets
    output: /assets
    rename: safe
    categories: [image]
  - name: public_assets
    label: Public assets
    input: public/assets
    output: /assets
    rename: safe
    categories: [image, video, audio]

content:
  - name: blog
    label: Blog
    type: collection
    path: content/blog
    format: yaml-frontmatter
    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: create
    exclude:
      - assets/**
    view:
      fields: [pubDate, title, description, draft]
      primary: pubDate
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: false
      - name: description
        label: Description
        type: text
        required: false
      - name: pubDate
        label: Publication date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: code
        options:
          format: markdown
settings:
  content:
    merge: true
