media:
  - name: blog_assets
    label: Blog assets
    input: public/assets
    output: /assets
    rename: safe
    categories: [image]
  - name: public_assets
    label: Public assets
    input: public/assets
    output: /assets
    rename: safe
    categories: [image, video, audio]

content:
  - name: blog
    label: Blog
    type: collection
    path: content/blog
    format: yaml-frontmatter
    filename: "{year}-{month}-{day}-{primary}.md"
    exclude:
      - assets/**
    view:
      fields: [title, pubDate, draft]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
      - name: pubDate
        label: Publication date
        type: date
        required: true
      - name: draft
        label: Draft
        type: boolean
      - name: body
        label: Body
        type: rich-text
        options:
          format: markdown
          media: blog_assets
          switcher: true
settings:
  content:
    merge: true
