media:
  - name: assets
    label: Assets
    input: public/assets
    output: /assets
    rename: safe
    categories: [image, video]
    extensions: [avif, jpg, jpeg, png, webp, m4v, mov, mp4, webm]
    actions:
      - name: optimize-media
        label: Optimize media
        workflow: pages-cms-media.yml
        ref: current
        cancelable: false

content:
  - name: blog
    label: Blog
    type: collection
    path: content/blog
    format: yaml-frontmatter
    filename:
      template: "{year}-{month}-{day}-{title}.md"
      field: create
    exclude:
      - assets/**
      - _*.md
    view:
      fields: [pubDate, title, description, draft]
      primary: pubDate
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
    fields:
      - name: title
        label: Title
        type: string
        required: false
      - name: description
        label: Description
        type: text
        required: false
      - name: pubDate
        label: Publication date
        type: date
        required: true
        options:
          format: yyyy-MM-dd
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Markdown / HTML
        type: code
        options:
          format: markdown
settings:
  content:
    merge: true

actions:
  - name: deploy-site
    label: Deploy site
    workflow: deploy.yml
    ref: current
    cancelable: false
