name: Deploy

on:
  workflow_dispatch:
    inputs:
      payload:
        description: Pages CMS payload as JSON
        required: false
        type: string
  push:
    branches:
      - main

env:
  CI: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: nubjs/setup-nub@21b317c170eee658503996209cf87b63481be35a # v0.5.0
        with:
          node-version-file: package.json
          cache: true
      - name: Install dependencies
        run: nub install
      - name: Build
        run: nub run build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@ebbaa1584979971c8614a24965b4405ff95890e0 # v4.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=${{ secrets.CLOUDFLARE_SITE_ID }}
      - name: Print deployment URL
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
