name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - sanity-content-update
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build
        env:
          SANITY_PROJECT_ID: ${{ vars.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ vars.SANITY_DATASET }}
          SANITY_API_VERSION: ${{ vars.SANITY_API_VERSION }}
        run: pnpm run build
      - name: Deploy
        id: deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist/ --project-name=${{ secrets.CLOUDFLARE_SITE_ID }}
      - name: Print deployment URL
        env:
          DEPLOYMENT_URL: ${{ steps.deploy.outputs.deployment-url }}
        run: echo $DEPLOYMENT_URL
